### ISSUE TITLE
die function does not exist

### ISSUE THREAD

**Issue by m47730** [funtoo/metro#18]
Hi,
i received an error of misconfiguration when compiling stage1, but gives me "die command not found". Looking at ${tmpmetro}/tmp/steps/chroot/run.metro i see a lot of "[...] || die [...]" lines, but no die functions.

i suppose something like:

function die()
{
echo ${@}
exit 2
}

is desiderable.
I haven't found any source or include in the file, but maybe i'm missing something.

Regards,
Matteo

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1978

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2036

**Comment by tecem** [comment]
thank you for not giving up on this bug!
But, is not a dupe? :-)

https://bugs.funtoo.org/browse/FL-1978
https://bugs.funtoo.org/browse/FL-2036

**Comment by danielrobbins** [comment]
Yes, I need to work on the GitHub integration script -- every new comment generates a new "issue" in the queue -- so we're gettin' dupes :) Sorry about that. Will fix it soon.

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
